
default: &default
  adapter: postgresql
  encoding: unicode
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gym_fitness_api_development

  
test:
  <<: *default
  database: gym_fitness_api_test


production:
  <<: *default
  database: gym_fitness_api_production
  username: gym_fitness_api
  password: <%= ENV["GYM_FITNESS_API_DATABASE_PASSWORD"] %>
